function Species (sci_name, com_name, rec_author, rec_number) {
	this.sci_name = sci_name;
	this.com_name = com_name;
	this.rec_author = rec_author;
	this.rec_number = rec_number;
	this.com_name_f = function () { return capitalize_words(this.com_name); }
	this.sci_name_f = function () { return capitalize(this.sci_name.replace(/-/g, ' ')); }
	this.audio_uri = function () { return '../songs/' + this.sci_name + '.mp3'; }
	this.img_uri = function () { return '../pics/' + this.sci_name + '.jpg'; }
}

var species_list = [
	new Species('oriolus-oriolus', 'golden oriole', 'Mathias Ritschard', '30187'),
	new Species('lanius-collurio', 'red-backed shrike', 'Volker Arnold', '72627'),
	new Species('pyrrhocorax-pyrrhocorax', 'chough', 'Olivier Grosselet', '55319'),
	new Species('garrulus-glandarius', 'jay', 'Niels Krabbe', '25647'),
	new Species('pica-pica', 'magpie', 'Stuart Fisher', '42388'),
	new Species('coloeus-monedula', 'jackdaw', 'Patrik Åberg', '42332'),
	new Species('corvus-frugilegus', 'rook', 'Patrik Åberg', '27146'),
	new Species('corvus-corax', 'raven', 'Jordi Calvet', '57509'),
	new Species('corvus-corone', 'carrion crow', 'Stuart Fisher', '28238'),
	new Species('corvus-cornix', 'hooded crow', 'Stuart Fisher', '28238'),
	new Species('cyanistes-caeruleus', 'blue tit', 'Patrik Åberg', '28208'),
	new Species('parus-major', 'great tit', 'Stein Ø. Nilsen', '45953'),
	new Species('periparus-ater', 'coal tit', 'Stuart Fisher', '24884'),
	new Species('lophophanes-cristatus', 'crested tit', 'Matthias Feuersenger', '46279'),
	new Species('poecile-montana', 'willow tit', 'Patrik Åberg', '28199'),
	new Species('poecile-palustris', 'marsh tit', 'Ruud van Beusekom', '27291'),
	new Species('panurus-biarmicus', 'bearded tit', 'Niels Krabbe', '25560'),
	new Species('alauda-arvensis', 'skylark', 'Patrik Åberg', '27004'),
	new Species('lullula-arborea', 'woodlark', 'Patrik Åberg', '42605'),
	new Species('locustella-luscinioides', 'Savi\'s warbler', 'Mathias Ritschard', '29775'),
	new Species('locustella-naevia', 'grasshopper warbler', 'Patrik Åberg', '26936'),
	new Species('acrocephalus-paludicola', 'aquatic warbler', 'Niels Krabbe', '24869'),
	new Species('acrocephalus-schoenobaenus', 'sedge warbler', 'Patrik Åberg', '27120'),
	new Species('acrocephalus-palustris', 'marsh warbler', 'Stuart Fisher', '24803'),
	new Species('acrocephalus-scirpaceus', 'reed warbler', 'Patrik Åberg', '27122'),
	new Species('riparia-riparia', 'sand martin', 'Patrik Åberg', '27277'),
	new Species('hirundo-rustica', 'swallow', 'Tomas Belka', '36375'),
	new Species('delichon-urbicum', 'house martin', 'Patrik Åberg', '27279'),
	new Species('sylvia-atricapilla', 'blackcap', 'Mathias Ritschard', '29723'),
	new Species('sylvia-borin', 'garden warbler', 'Mathias Ritschard', '30101'),
	new Species('sylvia-curruca', 'lesser whitethroat', 'Patrik Åberg', '27139'),
	new Species('sylvia-communis', 'whitethroat', 'Bas van de Meulengraaf', '34094'),
	new Species('sylvia-undata', 'Dartford warbler', 'Manuel Grosselet', '54914'),
	new Species('aegithalos-caudatus', 'long-tailed tit', 'Patrik Åberg', '28192'),
	new Species('cettia-cetti', 'Cetti\'s warbler', 'Jordi Calvet', '40233'),
	new Species('phylloscopus-sibilatrix', 'wood warbler', 'Patrik Åberg', '42289'),
	new Species('phylloscopus-collybita', 'chiffchaff', 'Patrik Åberg', '26762'),
	new Species('phylloscopus-trochilus', 'willow warbler', 'Patrik Åberg', '26756'),
	new Species('bombycilla-garrulus', 'waxwing', 'Patrik Åberg', '27110'),
	new Species('regulus-ignicapilla', 'firecrest', 'Patrik Åberg', '34047'),
	new Species('regulus-regulus', 'goldcrest', 'Patrik Åberg', '42341'),
	new Species('sitta-europaea', 'nuthatch', 'Sander Bot', '35043'),
	new Species('certhia-brachydactyla', 'short-toed treecreeper', 'Ukolov Ilya', '30552'),
	new Species('certhia-familiaris', 'treecreeper', 'Volker Arnold', '72675'),
	new Species('troglodytes-troglodytes', 'wren', 'Patrik Åberg', '27114'),
	new Species('sturnus-vulgaris', 'starling', 'Patrik Åberg', '27154'),
	new Species('cinclus-cinclus', 'dipper', 'Patrik Åberg', '29601'),
	new Species('turdus-viscivorus', 'mistle thrush', 'Patrik Åberg', '26978'),
	new Species('turdus-philomelos', 'song thrush', 'Patrik Åberg', '26981'),
	new Species('turdus-iliacus', 'redwing', 'Patrik Åberg', '42438'),
	new Species('turdus-merula', 'blackbird', 'Niels Krabbe', '25554'),
	new Species('turdus-pilaris', 'fieldfare', 'Niels Krabbe', '25765'),
	new Species('turdus-torquatus', 'ring ouzel', 'Christoph Bock', '55410'),
	new Species('muscicapa-striata', 'spotted flycatcher', 'Patrik Åberg', '27529'),
	new Species('erithacus-rubecula', 'robin', 'Patrik Åberg', '27554'),
	new Species('luscinia-megarhynchos', 'nightingale', 'Mathias Ritschard', '29724'),
	new Species('luscinia-svecica', 'bluethroat', 'Krystian Zwolinski', '33965'),
	new Species('ficedula-hypoleuca', 'pied flycatcher', 'Patrik Åberg', '27521'),
	new Species('phoenicurus-ochruros', 'black redstart', 'Niels Krabbe', '25584'),
	new Species('phoenicurus-phoenicurus', 'redstart', 'Patrik Åberg', '27565'),
	new Species('oenanthe-oenanthe', 'wheatear', 'Herman van Oosten', '35411'),
	new Species('saxicola-rubetra', 'whinchat', 'Patrik Åberg', '27571'),
	new Species('saxicola-rubicola', 'stonechat', 'Herman van Oosten', '34070'),
	new Species('prunella-modularis', 'dunnock', 'Patrik Åberg', '27116'),
	new Species('passer-domesticus', 'house sparrow', 'Jarek Matusiak', '44727'),
	new Species('passer-montanus', 'tree sparrow', 'Jarek Matusiak', '42213'),
	new Species('motacilla-alba', 'pied wagtail', 'Tomas Belka', '35533'),
	new Species('motacilla-flava', 'yellow wagtail', 'Marc Schweitzer', '34042'),
	new Species('motacilla-cinerea', 'grey wagtail', 'Patrik Åberg', '27019'),
	new Species('anthus-pratensis', 'meadow pipit', 'Ruud van Beusekom', '30614'),
	new Species('anthus-petrosus', 'rock pipit', 'Herman van Oosten', '39339'),
	new Species('anthus-trivialis', 'tree pipit', 'Patrik Åberg', '27016'),
	new Species('fringilla-coelebs', 'chaffinch', 'Patrik Åberg', '27602'),
	new Species('fringilla-montifringilla', 'brambling', 'Stuart Fisher', '24726'),
	new Species('coccothraustes-coccothraustes', 'hawfinch', 'Patrik Åberg', '42561'),
	new Species('pyrrhula-pyrrhula', 'bullfinch', 'Niels Krabbe', '25564'),
	new Species('chloris-chloris', 'greenfinch', 'Sander Bot', '35048'),
	new Species('carpodacus-erythrinus', 'scarlet rosefinch', 'Patrik Åberg', '27694'),
	new Species('carduelis-carduelis', 'goldfinch', 'Ruud van Beusekom', '34678'),
	new Species('spinus-spinus', 'siskin', 'Sander Bot', '35044'),
	new Species('serinus-serinus', 'serin', 'Patrik Åberg', '42292'),
	new Species('loxia-curvirostra', 'crossbill', 'Ruud van Beusekom', '30574'),
	new Species('linaria-cannabina', 'linnet', 'Sander Bot', '35189'),
	new Species('linaria-flavirostris', 'twite', 'Patrik Åberg', '27692'),
	new Species('calcarius-lapponicus', 'Lapland bunting', 'Patik Åberg', '58552'),
	new Species('plectrophenax-nivalis', 'snow bunting', 'Dougie Preston', '48183'),
	new Species('emberiza-schoeniclus', 'reed bunting', 'Patrik Åberg', '27598'),
	new Species('emberiza-calandra', 'corn bunting', 'Stuart Fisher', '25929'),
	new Species('emberiza-citrinella', 'yellowhammer', 'Patrik Åberg', '27577'),
	new Species('emberiza-cirlus', 'cirl bunting', 'Mathias Ritschard', '29456')
];